name: Auto-Trigger Build Joomla Package

on:
  repository_dispatch:
    types: [auto-build]

jobs:
  trigger_build:
    runs-on: ubuntu-latest
    steps:
      - name: Запустить Build Joomla Package
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"event_type": "auto-build"}' \
          https://api.github.com/repos/${{ github.repository }}/dispatches
