name: Create ZIP without Root Folder

on:
  push:
    branches:
      - main

jobs:
  create-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install zip
      run: sudo apt-get install zip

    - name: Create ZIP without root folder
      run: |
        mkdir temp
        cp -r * temp
        cd temp
        zip -r ../archive.zip .
    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: archive
        path: archive.zip
